### PR TITLE
CTCP-1312: Dynamic title/heading on remove office of transit page.

### PR DESCRIPTION
**Pull request by jackheslop96**
- create a dynamic heading for the 'remove office of transit' page
- if the office name has not been answered, the text will read "Are you sure you want to remove this office of transit?"

### CODE REVIEW

**Review by ajchilts — COMMENTED** [review]
@jackheslop96  - is this something we need to consider for CYA too?

**Comment by jackheslop96** [comment]
> @jackheslop96 - is this something we need to consider for CYA too?

Fortunately this is something we considered for the 'add another' page. It currently just puts the country as the label if that is the only information it has for that particular office.

**Comment by jackheslop96** [comment]
> > @jackheslop96 - is this something we need to consider for CYA too?
> 
> Fortunately this is something we considered for the 'add another' page. It currently just puts the country as the label if that is the only information it has for that particular office.


https://user-images.githubusercontent.com/43777106/192256372-87dc7015-b1ca-4221-b8a3-a79103a4ee59.mov

**Review by ajchilts — APPROVED** [review]
LGTM

**Pull request merged**
